### ISSUE TITLE
Error importing tags...

### ISSUE THREAD

**Issue by jonffh** [jlbcontrols/Flintium#207]
Hi, 
Following:
Option 2: Development Setup, 
I get the following error while refreshing tags on ExportImportTags:
````
Traceback (most recent call last):
  File "<custom-function updateDataAsync>", line 10, in refresh
  File "<custom-function getDataset>", line 24, in getDataset
  File "<custom-function getPathList>", line 55, in getPathList
  File "<custom-function getPathList>", line 45, in addPathsRecursive
  File "<custom-function getPathList>", line 45, in addPathsRecursive
  File "<custom-function getPathList>", line 45, in addPathsRecursive
  File "<custom-function getPathList>", line 45, in addPathsRecursive
  File "<custom-function getPathList>", line 45, in addPathsRecursive
  File "<custom-function getPathList>", line 45, in addPathsRecursive
  File "<custom-function getPathList>", line 31, in addPathsRecursive
com.inductiveautomation.ignition.common.tags.paths.parser.TagPathFormatException: com.inductiveautomation.ignition.common.tags.paths.parser.TagPathFormatException: Illegal character '@' (Line 1 , Char 51)

	caused by TagPathFormatException: Illegal character '@' (Line 1 , Char 51)
```
`
Running code from the Git repo, on win2016 server, Ignition v. 8.0.17. 

Any pointers?

**Comment by jonffh** [comment]
So...funny story...it was simply a tag created ages ago when playing the first time with ignition. It had an @ sign in it, which apparently is not good for some reason....well there you go...

**Comment by jlbcontrols** [comment]
Sounds good, we're you able to get your test system up and running?

**Comment by jonffh** [comment]
Yes, looks like i'm up and running, thanks for following up. I don't have an emulator or an empty controller to play with atm, but I guess i'll figure out the merging back part as I go along :)  The library contains most of the items I need for now but i'm guessing we'll want some additions soon enough.
